//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.22 at 09:46:57 AM CEST 
//


package fr.treeptik.annuaire.jaxb;

import java.util.Date;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fr.treeptik.annuaire.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.treeptik.annuaire.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Numero }
     * 
     */
    public Numero createNumero() {
        return new Numero();
    }

    /**
     * Create an instance of {@link Annuaire }
     * 
     */
    public Annuaire createAnnuaire() {
        return new Annuaire();
    }

    /**
     * Create an instance of {@link Personne }
     * 
     */
    public Personne createPersonne(int id, String nom, String prenom, Date dateNaissance) {
        return new Personne(id, nom, prenom,dateNaissance);
    }

}
