//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.22 at 09:46:57 AM CEST 
//


package fr.treeptik.annuaire.jaxb;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="prenom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateNaissance" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element ref="{}numero" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "nom",
    "prenom",
    "dateNaissance",
    "numeros"
})
@XmlRootElement(name = "personne")
@Entity
@Table(name="T_Person")
public class Personne {

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
    protected int id;
    @XmlElement(required = true)
	@Column(name="lastName", length=50)
    protected String nom;
    @XmlElement(required = true)
	@Column(name="firstName", length=50)
    protected String prenom;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
	@Column(name="birthday")
	@Temporal(TemporalType.DATE)
    protected Date dateNaissance;
    
    //type est nécessaire pour lié cette attribut à la bonne classe
    @XmlElement(required = true, name="numero", type=Numero.class)
//	@Transient
	@OneToMany
    protected List<Numero> numeros;

    

	public Personne() {
		super();
	}
    
	public Personne(String nom, String prenom, Date dateNaissance,
			List<Numero> numeros) {
		super();
		this.nom = nom;
		this.prenom = prenom;
		this.dateNaissance = dateNaissance;
		this.numeros = numeros;
	}
	


	public Personne(int id, String nom, String prenom,
			Date dateNaissance) {
		super();
		this.id = id;
		this.nom = nom;
		this.prenom = prenom;
		this.dateNaissance = dateNaissance;
	}
	
    
    
    public Personne(int id, String nom, String prenom, Date dateNaissance,
			List<Numero> numeros) {
		super();
		this.id = id;
		this.nom = nom;
		this.prenom = prenom;
		this.dateNaissance = dateNaissance;
		this.numeros = numeros;
	}

	/**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the nom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNom() {
        return nom;
    }

    /**
     * Sets the value of the nom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNom(String value) {
        this.nom = value;
    }

    /**
     * Gets the value of the prenom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrenom() {
        return prenom;
    }

    /**
     * Sets the value of the prenom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrenom(String value) {
        this.prenom = value;
    }

  

    /**
	 * @return the dateNaissance
	 */
	public Date getDateNaissance() {
		return dateNaissance;
	}

	/**
	 * @param dateNaissance the dateNaissance to set
	 */
	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	/**
     * Gets the value of the numero property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the numero property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNumero().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Numero }
     * 
     * 
     */
    public List<Numero> getNumeros() {
        if (numeros == null) {
            numeros = new ArrayList<Numero>();
        }
        return this.numeros;
    }

	/**
	 * @param numero the numero to set
	 */
	public void setNumeros(List<Numero> numeros) {
		this.numeros = numeros;
	}









}
